/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type AnimalHouseResponsePet = Cat | Dog | Ant[];

export type AnimalHouseResponseMammalia = Cat | Dog;

export interface AnimalHouseResponse {
  pet: AnimalHouseResponsePet;
  mammalia: AnimalHouseResponseMammalia;
}

export interface Ant {
  name: string;
  ant_type: string;
}

export interface Cat {
  name: string;
  meow_volume: number;
}

export interface Dog {
  name: string;
  bark_volume: number;
}

/**
 * @summary Get Animal House
 */
export const getAnimalHouseAnimalHouseGet = <TData = AxiosResponse<AnimalHouseResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/animal-house`,options
    );
  }

export type GetAnimalHouseAnimalHouseGetResult = AxiosResponse<AnimalHouseResponse>
